version: "3.7"
services:

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sic parvis magna
      MYSQL_DATABASE: new_flask_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - flask_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pSic parvis magna"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: web
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL= 'mysql+pymysql://user:password@mariadb:3306/new_flask_db'
      - DATABASE_HOST=mariadb
      - DATABASE_PORT=3306
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_DB=new_flask_db
      - DEBUG="0"
    networks:
      - flask_network
    depends_on:
      - mariadb


  proxy:
    build: proxy
    restart: always
    ports:
      - "90:80"
    networks:
      - flask_network
    depends_on:
      - web



networks:
  flask_network:

volumes:
  mariadb_data:
